server:
  port: ${APP_PORT:18010}
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${API_ENV_KAFKA_SERVER:192.168.100.6:29092}
          defaultBrokerPort: 29092
  application:
    name: authorization
  datasource:
    url: jdbc:postgresql://${ENV_DB_HOST:192.168.100.6}:${ENV_DB_PORT:5433}/${ENV_DB_NAME:superbridge} #?createDatabaseIfNotExist=true
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      continue-on-error: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST_IP:127.0.0.1}:8093/eureka/
logging:
  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS XXX'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} | ${app.name} | ${app.version} | %-20.20thread | %5p | %-25.25logger{25} : %m%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} | ${app.name} | ${app.version} | %-20.20thread | %5p | %-25.25logger{25} : %m%n'
  level:
    root: INFO
    org:
      sla:
        globalapi: DEBUG
  file:
    name: ${API_ENV_LOG_PATH:/home/datadrive/logs/AUTH_SERVER/}${API_ENV_LOGFILE:today.log}
  logback:
    rollingpolicy:
      file-name-pattern: ${API_ENV_LOG_PATH:/home/datadrive/logs/AUTH_SERVER/}%d{ddMMyyyy}.%i.log
      max-history: 700
      max-file-size: 900MB
app:
  env: ${APP_ENV:TEST}
  name: AUTH-SERVER
  description: AUTH SERVER
  version: 1.0.0
  broker_key: ${API_ENV_BROKER_KEY:test}
  broker_encrypt_key: ${API_ENV_BROKER_ENCRYPT_KEY:test}
  smtp_host: ${APP_E_SMTP_HOST:smtp.office365.com}
  smtp_port: ${APP_E_SMTP_PORT:587}
  email_username: ${APP_E_USERNAME:alerts@switchlinkafrica.co.ke}
  email_password: ${APP_E_PASSWORD:$e!$V0%oY7Qm0g}
  is_app_live: false
  pvt_key: vNFe/V82sn4LNwrzKASJVoHrvhyFu6Z4aqtTv5CCI/PUI3W0H/GrhkahyAlqjCuEukhNjqyRRFf/+JlEnWtlltLH7IukNJRL7z+tAAGRngleAnxQPGRm0cVeEgqb3nmLTCjcjUzDn+H5Zpwj9WG39uZATPOPY+IEeEVNaWT4v4yvBvoX1yWQJ3dgpZ7YtVpqcv56qoMk2ygWU/Yzf4nx4myZ2P+IjSHewMWei9RrhtcThQg7az+c4G7XkIYfAfKJlHuLqHpYzUilr5wX3gAeA4dAllok5xlycxB+Q9uYpX8YLe/+sCKDsO3X4quShatY55XZng1GuP8/B1yvDgSRpRJaqmU2AdhRVchxi+SlXj42wZtAi7SMhzZK/GHJJqsQsD50W365fqWAFvJxQwum3aw5RkV7Lc6kcLs8tmS+yoBQ54YGxkEnog9zIy16chG4oWhnW+cLEz80gSTp/L0FOxLTCvtC9CKdk9j+apa5YJRNEGcZQbgL9Nknntd7cpCsXt91wVHkLnJiFOQ4YOsYjvFjnZDUjmkwe+7WlVPFVm5+7YUzfOmfYaSusj50utyrekc4/JdBkJNhD5p00+pduuECG02+NJ0PZ7ZV0kvQYaxxZx0B8maID13xYIe8khVp17jCZrfdwCDONknvEnLo+LI/2o8Mti6ovflEfhYcY64pR7NWXCQQGoiuk/mYh95xW5BiGf5tV1Yolm/z/zKwZBKT/zPHLXHjSTzXlPJ/JdbWvg7zSXct4nVDNsO/PYUrZn38fPlC4jmDh6ovSz2QTXA+AtlFkWxMcCEVZCfn9+rEleS8VcouXT/SUxWX8wyhM5PiAEMID44v7ucF7ehA0vU4pUpqV7zxtWqrbDGzHIRu21gpI4yWQx/oWcchYs5Xs9I3yrx4IApbK/KyKVFN1asDQzoqpLPfz/ed79cMZ1BzjtDc4eC1x23p9pOisD7i8nYsiwYqergdF5KZghtZctG2Ql+aJXlYZ/9g4emvf7KtfekM8Oeltj1N7b6svdZni97zbBxQZsikq8sfvwMCQHLw8Q31Vma0F1yaWuA8cKCU5zFYSpClzKNqP8Oyv6fF6EKwe8yVlmj7jb4dpHt4Sb4S387GRA9AMxlabey8jFX5VJEMacHpvB4lpMctyP5v6jLn1GAVVZfMag4UIRdOeLMYGNqLN/M46Ru49Di08483un/S40im9A20btQxfK8x53aRg+vr6yzcPDk3kISomn9FFSoZFVG1Cc1XXQNJ1vrHfnhzMQiNHvH71bUXpWrm4XqF335H1Lu0/fE6ZAqgGLg/o30WvbRQK/dxrjzb0gsYVqIsb1LAF1fccXz3UjyhiW3rmH+7krro4qk0n3qOio7xBOBdVYmvFjFC6XceS/YUaUMIQy/eQlf/tTQUas+TLTfxP9JwY9o513Y5NllX2+Q5FmF6oK5MQkmznq85eDhJp0h6hbqPSm6dRwWsN+BxxoyO1Vl7B3Of5XhCLQV9Lg0oy9eVqbNlEAxhth1miQqShe6y4LI6CNVPj5+FImTYqgSltWt4ICap9hH0asjbPR0fR7WQRxhxz/WSydRzo6PfTRLpNNdM6NPpt7nqAu63UjiYIv8RbIz6JpHxdLxZw2PzlVLUzd0HIuWBbqRjn9s=
  pub_key: UPqsBujNjE/trLS0vOs+3rbmWh6uzYygYqftwCdVaKvFSvFEm1w2ADe7cQ38/w8G1zvFPZmfYQ/tqWxPU1MP6ysL+IY6ipSxT56FqXJxayti7HOg2Govp6RZOQ9s4IoNAV3/ZzwyATgLgWghOXLL/Dvj+p0ZjA5T4895lrBUWd4Y14FkQ4e3wmiUV8xeJ1aDP54VkINZ4SDvdM92jC4yUVXWUrBUXkV2bXEK3734OlJQI90Aeqe2yz36bzJJkiNcytwP1xVHz6SbKdoEDgkFkQ25dz5EH404pUlNyOYTxJB/UB0O1Bg1dPT1U6vfjT5R/Fai4T61IeXDdhIgZyLxTf1bKMuOeses6p5WqCOed27NQqmI+YEL/g9WdIutA+3q6yuMymWC3tNSRxb1b34fRA==